# Generated by Django 3.2.23 on 2024-01-27 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TiposExames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=70)),
                ('preco', models.FloatField()),
                ('tipo', models.CharField(choices=[('I', 'Exame de Imagem'), ('S', 'Exame de Sangue')], max_length=1)),
                ('disponivel', models.BooleanField(default=True)),
                ('horario_incial', models.IntegerField()),
                ('horario_final', models.IntegerField()),
            ],
        ),
    ]
